services:
  app:
    build: .
    volumes:
      - .:/home/user/app
      - /tmp/.X11-unix:/tmp/.X11-unix
    tty: true
    deploy:
      mode: replicated
      replicas: 3
    depends_on:
      - mqtt
  mqtt:
    image: toke/mosquitto